# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20171128_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_doc', models.TextField()),
                ('answer_score', models.IntegerField()),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'block',
            },
        ),
        migrations.CreateModel(
            name='Block_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'block_type',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_doc', models.TextField()),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(null=True)),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Office')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.User')),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('avg_attempt', models.IntegerField()),
                ('certificate_count', models.IntegerField()),
                ('note_count', models.IntegerField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Location')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Staff')),
            ],
            options={
                'db_table': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='Subtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countable_max', models.IntegerField()),
                ('medium_treshold', models.IntegerField()),
                ('minimum_treshold', models.IntegerField()),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Block')),
            ],
            options={
                'db_table': 'subtest',
            },
        ),
        migrations.CreateModel(
            name='Subtest_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtest_type_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'subtest_type',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Result')),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.AddField(
            model_name='subtest',
            name='subtest_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Subtest_type'),
        ),
        migrations.AddField(
            model_name='question',
            name='subtest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Subtest'),
        ),
        migrations.AddField(
            model_name='block',
            name='block_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Block_type'),
        ),
        migrations.AddField(
            model_name='block',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Staff'),
        ),
        migrations.AddField(
            model_name='block',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Test'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Result'),
        ),
        migrations.AddField(
            model_name='answer',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Staff'),
        ),
    ]
